version: '2'
services:
  postgresql:
    image: bitnami/postgresql:11
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
  kong:
    image: bitnami/kong:2
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami
      
   konga-database:
    image: mongo:4.1.5
    container_name: konga-database
    volumes:
      - konga_data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/konga --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      
   konga:
    build: ./konga
    container_name: konga
    depends_on:
      konga-database:
        condition: service_healthy
    volumes:
      - ./konga/user_seed.js:/app/user_seed.js:ro
    ports:
      - 1337:1337
    environment:
      DB_ADAPTER: mongo
      DB_DATABASE: konga
      DB_HOST: konga-database
      KONGA_SEED_USER_DATA_SOURCE_FILE: /app/user_seed.js
      NODE_ENV: production
    restart: on-failure
volumes:
  konga_data:
  postgresql_data:
    driver: local
